module.exports = [
  {
    id: 1,
    name: 'Some Kind of Heaven',
    releaseDate: '15 January 2021',
    duration: '1h 21min',
    genre: 'Documentary',
    createdAt: '2020',
    description: 'Behind the gates of a palm tree-lined fantasyland, four residents of America\'s largest retirement community, The Villages, FL, strive to find solace and meaning.',
    director: 'Lance Oppenheim',
    stars: null,
    updatedAt: null
  },
  {
    id: 2,
    name: 'The Marksman',
    releaseDate: '21 January 2021',
    duration: '1h 48min',
    genre: 'Action, Thriller',
    createdAt: '2021',
    description: 'A rancher on the Arizona border becomes the unlikely defender of a young Mexican boy desperately fleeing the cartel assassins who\'ve pursued him into the U.S. ',
    director: 'Robert Lorenz',
    stars: 'Katheryn Winnick, Liam Neeson, Teresa Ruiz, Juan Pablo Raba',
    updatedAt: null
  },
  {
    id: 3,
    name: 'Don\'t Tell a Soul',
    releaseDate: '15 January 2021',
    duration: '1h 23min',
    genre: 'Drama, Thriller',
    createdAt: '2020',
    description: 'Two thieving teenage brothers, stealing money to help their sick mom, match wits with a troubled security guard stuck at the bottom of a forgotten well. ',
    director: 'Alex McAulay',
    stars: 'Fionn Whitehead, Jack Dylan Grazer, Mena Suvari, Rainn Wilson',
    updatedAt: null
  },
  {
    id: 4,
    name: 'Run Hide Fight',
    releaseDate: '14 January 2021',
    duration: '1h 49min',
    genre: 'Action',
    createdAt: '2020',
    description: '17-year-old Zoe Hull uses her wits, survival skills, and compassion to fight for her life, and those of her fellow classmates, against a group of live-streaming school shooters. ',
    director: 'Kyle Rankin',
    stars: 'Thomas Jane, Radha Mitchell, Isabel May, Eli Brown',
    updatedAt: null
  },
  {
    id: 5,
    name: 'The Friend',
    releaseDate: ' 22 January 2021',
    duration: '2h 4min',
    genre: 'Drama',
    createdAt: '2019',
    description: 'After receiving life-altering news, a couple finds unexpected support from their best friend, who puts his own life on hold and moves into their family home, bringing an impact much greater and more profound than anyone could have imagined',
    director: 'Gabriela Cowperthwaite',
    stars: 'Dakota Johnson, Gwendoline Christie, Casey Affleck',
    updatedAt: null
  },
  {
    id: 6,
    name: 'Breaking Fast',
    releaseDate: '22 January 2021',
    duration: '1h 32min',
    genre: 'Comedy, Drama',
    createdAt: '2020',
    description: 'Mo, a practicing Muslim living in West Hollywood, is learning to navigate life post heartbreak. Enter Kal, an All-American guy who surprises Mo by offering to break fast with him during the holy month of Ramadan.',
    director: 'Mike Mosallam',
    stars: 'Haaz Sleiman, Michael Cassidy, Amin El Gamal',
    updatedAt: null
  },
  {
    id: 7,
    name: 'The Little Things',
    releaseDate: '29 January 2021',
    duration: '2h 7m',
    genre: 'Crime, Drama, Thriller',
    createdAt: '2021',
    description: 'Two cops track down a serial killer.',
    director: 'John Lee Hancock',
    stars: 'Denzel Washington, Rami Malek, Jared Leto',
    updatedAt: null
  },
  {
    id: 8,
    name: 'The Night',
    releaseDate: '29 January 2021',
    duration: '1h 45min',
    genre: 'Horror, Mystery, Thriller',
    createdAt: '2020',
    description: 'An Iranian couple living in the US become trapped inside a hotel when insidious events force them to face the secrets that have come between them, in a night that never ends.',
    director: 'Kourosh Ahari',
    stars: 'Shahab Hosseini, Niousha Noor, George Maguire',
    updatedAt: null
  },
  {
    id: 9,
    name: 'Minamata',
    releaseDate: '13 March 2020',
    duration: '1h 55min',
    genre: 'Drama',
    createdAt: '2020',
    description: 'War photographer W. Eugene Smith travels back to Japan where he documents the devastating effect of mercury poisoning in coastal communities.',
    director: 'Andrew Levitas',
    stars: 'Johnny Depp, Bill Nighy, Hiroyuki Sanada',
    updatedAt: null
  },
  {
    id: 10,
    name: 'Judas and the Black Messiah',
    releaseDate: '12 February 2021',
    duration: '2h 6m',
    genre: 'Biography, Drama, History',
    createdAt: '2021',
    description: 'The story of Fred Hampton, Chairman of the Illinois Black Panther Party, and his fateful betrayal by FBI informant William O\'Neal.',
    director: 'Shaka King',
    stars: 'Daniel Kaluuya, LaKeith Stanfield, Jesse Plemons',
    updatedAt: null
  },
  {
    id: 11,
    name: 'French Exit',
    releaseDate: '26 February 2021',
    duration: '1h 50min',
    genre: 'Comedy, Drama',
    createdAt: '2020',
    description: 'An aging Manhattan socialite living on what\'s barely left of her inheritance moves to a small apartment in Paris with her son and cat. ',
    director: 'Azazel Jacobs',
    stars: 'Michelle Pfeiffer, Lucas Hedges, Tracy Letts',
    updatedAt: null
  }, {
    id: 12,
    name: 'Tom and Jerry',
    releaseDate: '11 February 2021',
    duration: null,
    genre: 'Comedy, Animation, Adventure',
    createdAt: '2021',
    description: 'Adaption of the classic Hanna-Barbera property, which reveals how Tom and Jerry first meet and form their rivalry.',
    director: 'Tim Story',
    stars: 'Chloë Grace Moretz, Michael Peña, Rob Delaney',
    updatedAt: null
  },
  {
    id: 13,
    name: 'Nobody',
    releaseDate: '26 February 2021',
    duration: '1h 32min',
    genre: 'Action, Crime, Drama',
    createdAt: '2021',
    description: 'A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.',
    director: 'Ilya Naishuller',
    stars: 'Bob Odenkirk, Connie Nielsen, Christopher Lloyd',
    updatedAt: null
  },
  {
    id: 14,
    name: 'Chaos Walking',
    releaseDate: '5 March 2021',
    duration: '1h 48m',
    genre: 'Adventure, Sci-Fi',
    createdAt: '2021',
    description: 'A dystopian world where there are no women and all living creatures can hear each other\'s thoughts in a stream of images, words, and sounds called Noise.',
    director: 'Doug Liman',
    stars: 'Tom Holland, Mads Mikkelsen, Daisy Ridley',
    updatedAt: null
  },
  {
    id: 15,
    name: 'Raya and the Last Dragon',
    releaseDate: '10 March 2021',
    duration: null,
    genre: 'Animation, Action, Adventure',
    createdAt: '2021',
    description: 'In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.',
    director: 'Don Hall, Carlos López Estrada',
    stars: 'Kelly Marie Tran, Awkwafina',
    updatedAt: null
  },
  {
    id: 16,
    name: 'The King\'s Man',
    releaseDate: '12 March 2021',
    duration: '2h 11m',
    genre: 'Action, Adventure, Comedy',
    createdAt: '2021',
    description: 'In the early years of the 20th century, the Kingsman agency is formed to stand against a cabal plotting a war to wipe out millions.',
    director: 'Matthew Vaughn',
    stars: 'Matthew Goode, Gemma Arterton, Aaron Taylor-Johnson',
    updatedAt: null
  },
  {
    id: 17,
    name: 'Godzilla vs. Kong',
    releaseDate: '26 March 2021',
    duration: null,
    genre: 'Action, Sci-Fi, Thriller',
    createdAt: '2021',
    description: 'The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.',
    director: 'Adam Wingard',
    stars: 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall',
    updatedAt: null
  },
  {
    id: 18,
    name: 'No Time to Die',
    releaseDate: '31 March 2021',
    duration: ' 2h 43min',
    genre: 'Action, Adventure, Thriller',
    createdAt: '2021',
    description: 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
    director: 'Cary Joji Fukunaga',
    stars: 'Daniel Craig, Ana de Armas, Rami Malek',
    updatedAt: null
  },
  {
    id: 19,
    name: 'A Quiet Place Part II',
    releaseDate: '21 April 2021',
    duration: '1h 37min',
    genre: 'Drama, Horror, Sci-Fi',
    createdAt: '2021',
    description: 'Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path.',
    director: 'John Krasinski',
    stars: 'Emily Blunt, Millicent Simmonds, Cillian Murphy',
    updatedAt: null
  },
  {
    id: 20,
    name: 'Black Widow',
    releaseDate: '5 May 2021',
    duration: null,
    genre: 'Action, Adventure, Sci-Fi',
    createdAt: '2021',
    description: 'A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.',
    director: 'Cate Shortland',
    stars: 'Scarlett Johansson, Florence Pugh, David Harbour',
    updatedAt: null
  },
  {
    id: 21,
    name: 'Rumble',
    releaseDate: '14 May 2021',
    duration: null,
    genre: 'Animation, Comedy, Family',
    createdAt: '2021',
    description: 'In a world where monster wrestling is a global sport and monsters are superstar athletes, teenage Winnie seeks to follow in her father\'s footsteps by coaching a loveable underdog monster into a champion.',
    director: 'Hamish Grieve',
    stars: 'Ben Schwartz, Terry Crews, Will Arnett',
    updatedAt: null
  },
  {
    id: 22,
    name: 'Free Guy',
    releaseDate: '21 May 2021',
    duration: null,
    genre: 'Action, Adventure, Comedy',
    createdAt: '2021',
    description: 'A bank teller discovers that he\'s actually an NPC inside a brutal, open world video game.',
    director: 'Shawn Levy',
    stars: 'Ryan Reynolds, Jodie Comer, Taika Waititi',
    updatedAt: null
  },
  {
    id: 23,
    name: 'F9',
    releaseDate: '28 May 2021',
    duration: '2h 25min',
    genre: 'Action, Adventure, Crime',
    createdAt: '2021',
    description: 'Cypher enlists the help of Jakob, Dom\'s younger brother to take revenge on Dom and his team.',
    director: 'Justin Lin',
    stars: 'Vin Diesel, Michelle Rodriguez, Charlize Theron',
    updatedAt: null
  }
]
